### ISSUE TITLE
Upgrade Typescript compiler with latest Testcafe version

### ISSUE THREAD

**Issue by khanh-shady** [Arthy000/gherkin-testcafe#24] opened 2021-01-29 01:42 UTC
Recently, TestCafe released a new version (@v1.10.2-alpha.1) and they removed the [tsConfigPath](https://devexpress.github.io/testcafe/documentation/reference/configuration-file.html#tsconfigpath) function in favour of [compilerOptions](https://devexpress.github.io/testcafe/documentation/reference/configuration-file.html#compileroptions), also they specify TypeScript option to pass into their [TypeScript compiler
](https://github.com/DevExpress/testcafe/blob/v1.10.2-alpha.1/src/compiler/compilers.js)

It seems that this is the way it is from now on so do you think you can make an upgrade for this? Thank you very much!

**Comment by Arthy000** [comment] 2021-02-01 11:13
Hello,

I've only tested with testcafe@1.10.1 (the last stable release), however it looks like there is nothing to do on my side.
![image](https://user-images.githubusercontent.com/1800622/106451385-cb0db300-6486-11eb-9b61-26ff8abc2a9b.png)

Gherkin-testcafe does not use its own testcafe dependency, instead it requires a peer dependency; That means you are responsible for upgrading testcafe.

Do you have an issue that I can try to reproduce?

**Comment by khanh-shady** [comment] 2021-02-02 02:50
It's in their newest version (v1.10.2-alpha.1) and I think they will upgrade it soon as in their [documents](https://devexpress.github.io/testcafe/documentation/reference/configuration-file.html#tsconfigpath) clearly stated.

**Comment by Arthy000** [comment] 2021-02-02 08:57
tsConfigPath is
``` 
Deprecated as of TestCafe v.1.10.0 in favour of the compilerOptions setting.
```

So the change you refer to is already available in 1.10.1. As shown in the screenshot, the new option is available, provided that you upgrade your TestCafe dependency.

I'm not sure what you are expecting of me here.

**Comment by khanh-shady** [comment] 2021-02-02 11:00
The new [compilerOptions](https://github.com/DevExpress/testcafe/blob/v1.10.2-alpha.1/src/compiler/compilers.js#L13) have a typescript property which is not present right now in gherkin-testcafe, so we won't be able to pass our configuration file to it.

**Comment by Arthy000** [comment] 2021-02-02 11:32
That one?
![image](https://user-images.githubusercontent.com/1800622/106594685-be569100-6552-11eb-9218-23f970a531c2.png)

**Comment by khanh-shady** [comment] 2021-02-03 01:16
Yes!

**Comment by Arthy000** [comment] 2021-02-03 12:59
That's weird, the only thing I had to do was upgrade testcafe (1.10.1) in my personal project (NOT gherkin-testcafe).

Gherkin-testcafe keeps most of the runner object, it just adds a few functions and modifies one. Anything else is exported as is and should work without any change in this package.

I'm not sure what I can do, but I'm willing to help you figure this out.

**Comment by khanh-shady** [comment] 2021-02-04 02:02
Sorry I didn't make my point clear enough.

In gherkin-testcafe, we have our own [compiler](https://github.com/Arthy000/gherkin-testcafe/blob/develop/src/compiler.js#L58) which received our configs to pass to testcafe [compilers](https://github.com/Arthy000/gherkin-testcafe/blob/develop/src/compiler.js#L11). But in testcafe, they clearly changed how to receive our configs as you can see [here](https://github.com/DevExpress/testcafe/blob/v1.10.2-alpha.1/src/compiler/compilers.js#L13).

Testcafe get only the typescript property in configuration object to pass down to typescript compiler while gherkin-testcafe get the whole object and pass straight down.

**Comment by Arthy000** [comment] 2021-02-04 10:47
Sorry I didn't understand the issue sooner. 
Could you please try the branch linked to this issue?

**Comment by Andy2003** [comment] 2021-02-04 13:57
I think the sollution is to change https://github.com/Arthy000/gherkin-testcafe/blob/c55e0f813f24d6461860cb36ec0e4c8fb95cadb1/src/compiler.js#L58

to 
```js
new TestcafeTypescriptCompiler(compilerOptions.typescript)
```

**Comment by Andy2003** [comment] 2021-02-04 13:59
I tested the above change locally and my customized typescript compile config was successfully passed through

**Comment by khanh-shady** [comment] 2021-02-05 01:40
> I think the sollution is to change
> 
> https://github.com/Arthy000/gherkin-testcafe/blob/c55e0f813f24d6461860cb36ec0e4c8fb95cadb1/src/compiler.js#L58
> 
> to
> 
> ```js
> new TestcafeTypescriptCompiler(compilerOptions.typescript)
> ```

This is totally correct! I have to change it like this locally to pass my config through

**Comment by Andy2003** [comment] 2021-02-23 17:05
@Arthy000 when will this bug be fixed and released?

**Comment by Arthy000** [comment] 2021-02-25 07:28
Hello, 
I'm still waiting for confirmation that my branch does the work (it's almost the change you suggested, but not identical).
I'm hoping to release a new version tomorrow if I can solve another issue.

**Comment by Andy2003** [comment] 2021-02-25 07:31
@Arthy000 your branch will fix this issue!

**Comment by Arthy000** [comment] 2021-02-26 14:00
I just published a new version that contains the fix for this issue, as well as a fix for Unix users

**Closed by Arthy000** 2021-02-26 14:00 UTC
