### ISSUE TITLE
The "from" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by kel666** [Arthy000/gherkin-testcafe#85] opened 2022-05-31 10:21 UTC
After upgrading testcafe, gherkin-testcafe and cucumber, I'm getting this error when running tests:

```
PS C:\git\USP.Commodity.UI> npx gherkin-testcafe --skip-js-errors --compiler-options typescript.options.esModuleInterop=true chrome src/e2etest/**/*.ts .\src\e2etest\createProduct.feature
ERROR Cannot prepare tests due to the following error:

TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined    
    at Object.getDefinitionLineAndUri (C:\git\USP.Commodity.UI\node_modules\@cucumber\cucumber\src\support_code_library_builder\build_helpers.ts:21:18)
    at SupportCodeLibraryBuilder.defineStep (C:\git\USP.Commodity.UI\node_modules\@cucumber\cucumber\src\support_code_library_builder\index.ts:138:27)
    at Object.<anonymous> (C:\git\USP.Commodity.UI\src\e2etest\steps.ts:13:1)
    at C:\git\USP.Commodity.UI\node_modules\gherkin-testcafe\src\compiler.js:259:26
    at C:\git\USP.Commodity.UI\node_modules\gherkin-testcafe\src\compiler.js:258:17
    at GherkinTestcafeCompiler._loadStepDefinitions (C:\git\USP.Commodity.UI\node_modules\gherkin-testcafe\src\compiler.js:263:5)
    at GherkinTestcafeCompiler.getTests (C:\git\USP.Commodity.UI\node_modules\gherkin-testcafe\src\compiler.js:142:5)

```
Here's my package.json:

```
{
//...
  "dependencies": {
    "@ant-design/icons": "^4.6.2",
    "@craco/craco": "^6.4.3",
    "@microsoft/signalr": "^6.0.4",
    "@reduxjs/toolkit": "^1.8.1",
    "@types/jest": "^26.0.20",
    "@types/lodash": "^4.14.168",
    "@types/lz-string": "^1.3.34",
    "@types/mousetrap": "^1.6.5",
    "@types/node": "^12.20.1",
    "@types/react": "^17.0.43",
    "@types/react-dom": "^17.0.14",
    "@types/react-redux": "^7.1.24",
    "@types/react-router-dom": "^5.3.3",
    "@types/redux-logger": "^3.0.8",
    "@types/redux-mock-store": "^1.0.2",
    "@types/uuid": "^8.3.4",
    "antd": "^4.20.5",
    "antd-mask-input": "^2.0.7",
    "clsx": "^1.1.1",
    "core-js": "^3.8.3",
    "craco-antd": "^2.0.0",
    "exceljs": "^4.2.1",
    "file-saver": "^2.0.5",
    "html-to-image": "^1.9.0",
    "i18next": "^19.8.7",
    "lz-string": "^1.4.4",
    "moment": "^2.29.3",
    "moment-business": "^3.0.1",
    "mousetrap": "^1.6.5",
    "oidc-client": "^1.11.4",
    "react": "^18.1.0",
    "react-app-polyfill": "^2.0.0",
    "react-device-detect": "^1.17.0",
    "react-dom": "^18.1.0",
    "react-i18next": "^11.8.6",
    "react-number-format": "^4.4.4",
    "react-redux": "^8.0.2",
    "react-router-dom": "^6.0.0",
    "react-scripts": "^5.0.1",
    "react-tiny-fab": "^4.0.2",
    "redux": "^4.1.2",
    "redux-logger": "^3.0.6",
    "redux-oidc": "^4.0.0-beta1",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "ts-polyfill": "^3.8.2",
    "typescript": "^4.1.5",
    "uuid": "^8.3.2",
    "web-vitals": "^0.2.4"
  },
// ...
  "jest": {
    "snapshotSerializers": [
      "jest-serializer-html"
    ]
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
// ...
  "devDependencies": {
    "@cucumber/cucumber": "^7.3.1",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.2.0",
    "@testing-library/user-event": "^14.2.0",
    "@types/file-saver": "^2.0.2",
    "@types/moment-business": "^0.1.4",
    "eol-converter-cli": "^1.0.8",
    "eslint": "^7.20.0",
    "eslint-config-prettier": "^7.2.0",
    "eslint-plugin-prettier": "^3.3.1",
    "fetch-mock": "^9.11.0",
    "gherkin-testcafe": "^5.3.0",
    "glob": "^7.1.6",
    "jest-serializer-html": "^7.0.0",
    "prettier": "2.2.1",
    "redux-mock-store": "^1.5.4",
    "serve": "^11.3.2",
    "swagger-typescript-api": "^4.4.0",
    "testcafe": "^1.18.6",
    "testcafe-browser-provider-selenium": "^1.2.0"
  }
}

```

Any help will be appreciated.
Fabio

**Comment by Arthy000** [comment] 2022-06-01 06:17
Hi @kel666 

First thing first, did you remove `@cucumber/cucumber-expressions` from your project or is it an oversight when you copy pasted?

I'll work on your issue later today :)

**Comment by kel666** [comment] 2022-06-01 06:31
I removed it since I don't use it... I added it just as an attempt to see it would have fixed the issue.
Tnx a lot for your help

**Comment by Arthy000** [comment] 2022-06-01 08:49
Hello again, another possible source for your issue is that you have a mix between / and \ in the source paths in your command:
```
src/e2etest/**/*.ts .\src\e2etest\createProduct.feature
```

Working with bash, I always tend to use the / (unix path) instead of \; not really sure if PowerShell will have issue with either (I havent tried to reproduce the issue yet, I'm just trying to remove any source of error outside of the code)

**Comment by kel666** [comment] 2022-06-01 15:26
Tried both

npx gherkin-testcafe --skip-js-errors --compiler-options typescript.options.esModuleInterop=true chrome .\src\e2etest\**\*.ts .\src\e2etest\createProduct.feature
npx gherkin-testcafe --skip-js-errors --compiler-options typescript.options.esModuleInterop=true chrome ./src/e2etest/**/*.ts ./src/e2etest/createProduct.feature

but the error remains the same

**Comment by Arthy000** [comment] 2022-06-01 17:56
Just tried with the exact same dependencies, works like a charm :/
I defined a script in my `package.json`:
 ```
"kel666": "gherkin-testcafe --skip-js-errors --compiler-options typescript.options.esModuleInterop=true chrome ./examples/*.ts ./examples/*.feature"
```
Then when running it:
```
 Feature: Using custom parameter types
 ✖ Scenario: Searching for color in Google
   1) Error: Step implementation missing for: I am searching for the blue color on Google

 Feature: Datatable demo feature
 ✓ Scenario: Searching for Datatable by Google

 Feature: Doc string feature
 ✓ Scenario: Asserting page subtitle

 Feature: The big search feature
Running Google e2e test.
 ✓ Scenario: Searching for TestCafe by Google
 ✓ Scenario: Searching for facebook on Google
 ✓ Scenario: Searching for twitter on Google

 Feature: HTTP Basic Authentication
 ✓ Scenario: Authenticating on Jigsaw HTTP test site
```
(one test is failing because I didn't provide a custom typing file)

Could you please try to do the following:
1. Create a separate folder named `examples`
2. Create `google.ts` and `google.feature` in there
3. Copy the content from this repository `./examples/google.ts` and `./examples/google.feature`
4. Run the command
```
npx gherkin-testcafe chrome ./examples/*
```

### If you still get the issue
Then there is probably something wrong with your dependencies (make sure you don't have anything globally installed that could mess with your local dependencies)
Use `npm ls` and `npm ls -g` to see what versions of packages are really being used:
```
% npm ls
gtc-tester@1.0.0 /Users/arthurwarnier/gtc-tester
├── @cucumber/cucumber-expressions@12.1.3
├── @cucumber/cucumber@7.3.2
├── gherkin-testcafe@5.3.0
└── testcafe@1.18.6
```

### If you don't get the issue anymore
Then the issue is likely caused by the content of your files or the path you used in your command. In that case we can review them together if you'd like.

**Comment by kabomi** [comment] 2022-06-03 11:55
Hi,

I had also that problem with v5.3.1.
An update of package.json dependency to @cucumber/cucumber: "8.2.2" was necessary. 
When I did, it didn't workout well. But after removing node_modules and executing yarn again, the problem got solved.
I hope my experience can help you. I don't think that you can still use @cucumber v7 in your dependencies anymore.

Greetings

**Comment by Arthy000** [comment] 2022-06-03 19:14
That might be it, but if I remember correctly the cucumber peer dependency was still 7 when I released 5.3, I only updated it for 5.3.1

**Comment by kel666** [comment] 2022-06-07 10:05
Hellp Arthy, I tried with google example but still having same issue:

```
C:\git\USP.Commodity.UI>npx gherkin-testcafe chrome ./examples/*
ERROR Cannot prepare tests due to the following error:

TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined
    at Object.getDefinitionLineAndUri (C:\git\USP.Commodity.UI\node_modules\@cucumber\cucumber\src\support_code_library_builder\build_helpers.ts:21:18)
    at Object.Before (C:\git\USP.Commodity.UI\node_modules\@cucumber\cucumber\src\support_code_library_builder\index.ts:175:29)
    at Object.<anonymous> (C:\git\USP.Commodity.UI\examples\google.ts:12:1)
    at C:\git\USP.Commodity.UI\node_modules\gherkin-testcafe\src\compiler.js:259:26
    at C:\git\USP.Commodity.UI\node_modules\gherkin-testcafe\src\compiler.js:258:17
    at GherkinTestcafeCompiler._loadStepDefinitions (C:\git\USP.Commodity.UI\node_modules\gherkin-testcafe\src\compiler.js:263:5)
    at GherkinTestcafeCompiler.getTests (C:\git\USP.Commodity.UI\node_modules\gherkin-testcafe\src\compiler.js:142:5)

```

Following you can find my npm deps global and local, which looks good to me:

global
```
C:\Users\C331663\AppData\Roaming\npm
`-- yarn@1.22.17
```

local (depth 1)
```
commodity-ui@0.1.0 C:\git\USP.Commodity.UI
+-- @ant-design/icons@4.6.2
| +-- @ant-design/colors@6.0.0
| +-- @ant-design/icons-svg@4.1.0
| +-- @babel/runtime@7.12.5
| +-- classnames@2.2.6
| `-- rc-util@5.12.2
+-- @craco/craco@6.4.3
| +-- cosmiconfig@7.0.1
| +-- cosmiconfig-typescript-loader@1.0.9
| +-- cross-spawn@7.0.3
| +-- lodash@4.17.21
| +-- semver@7.3.2
| `-- webpack-merge@4.2.2
+-- @cucumber/cucumber@7.3.1
| +-- @cucumber/create-meta@5.0.0
| +-- @cucumber/cucumber-expressions@12.1.3
| +-- @cucumber/gherkin@19.0.3
| +-- @cucumber/gherkin-streams@2.0.2
| +-- @cucumber/html-formatter@15.0.2
| +-- @cucumber/messages@16.0.1
| +-- @cucumber/tag-expressions@3.0.1
| +-- assertion-error-formatter@3.0.0
| +-- bluebird@3.7.2
| +-- capital-case@1.0.4
| +-- cli-table3@0.6.2
| +-- colors@1.4.0
| +-- commander@7.2.0
| +-- create-require@1.1.1
| +-- duration@0.2.2
| +-- durations@3.4.2
| +-- figures@3.2.0
| +-- glob@7.1.6 deduped
| +-- indent-string@4.0.0
| +-- is-generator@1.0.3
| +-- is-stream@2.0.1
| +-- knuth-shuffle-seeded@1.0.6
| +-- lodash@4.17.21 deduped
| +-- mz@2.7.0
| +-- progress@2.0.3
| +-- resolve@1.22.0
| +-- resolve-pkg@2.0.0
| +-- stack-chain@2.0.0
| +-- stacktrace-js@2.0.2
| +-- string-argv@0.3.1
| +-- tmp@0.2.1
| +-- util-arity@1.1.0
| `-- verror@1.10.1
+-- @microsoft/signalr@6.0.4
| +-- abort-controller@3.0.0
| +-- eventsource@1.0.7
| +-- fetch-cookie@0.11.0
| +-- node-fetch@2.6.7
| `-- ws@7.5.7
+-- @reduxjs/toolkit@1.8.1
| +-- immer@9.0.12
| +-- redux@4.1.2 deduped
| +-- redux-thunk@2.4.1
| `-- reselect@4.1.5
+-- @testing-library/jest-dom@5.16.4
| +-- @babel/runtime@7.12.5 deduped
| +-- @types/testing-library__jest-dom@5.14.3
| +-- aria-query@5.0.0
| +-- chalk@3.0.0
| +-- css@3.0.0
| +-- css.escape@1.5.1
| +-- dom-accessibility-api@0.5.14
| +-- lodash@4.17.21 deduped
| `-- redent@3.0.0
+-- @testing-library/react@13.2.0
| +-- @babel/runtime@7.12.5 deduped
| +-- @testing-library/dom@8.13.0
| `-- @types/react-dom@18.0.4
+-- @testing-library/user-event@14.2.0
+-- @types/file-saver@2.0.2
+-- @types/jest@26.0.20
| +-- jest-diff@26.6.2
| `-- pretty-format@26.6.2
+-- @types/lodash@4.14.168
+-- @types/lz-string@1.3.34
+-- @types/moment-business@0.1.4
| `-- moment@2.29.3 deduped
+-- @types/mousetrap@1.6.5
+-- @types/node@12.20.1
+-- @types/react@17.0.43
| +-- @types/prop-types@15.7.4
| +-- @types/scheduler@0.16.2
| `-- csstype@3.0.11
+-- @types/react-dom@17.0.14
| `-- @types/react@17.0.43 deduped
+-- @types/react-redux@7.1.24
| +-- @types/hoist-non-react-statics@3.3.1
| +-- @types/react@17.0.43 deduped
| +-- hoist-non-react-statics@3.3.2
| `-- redux@4.1.2 deduped
+-- @types/react-router-dom@5.3.3
| +-- @types/history@4.7.11
| +-- @types/react@17.0.43 deduped
| `-- @types/react-router@5.1.18
+-- @types/redux-logger@3.0.8
| `-- redux@4.1.2 deduped
+-- @types/redux-mock-store@1.0.2
| `-- redux@4.1.2 deduped
+-- @types/uuid@8.3.4
+-- antd@4.20.5
| +-- @ant-design/colors@6.0.0 deduped
| +-- @ant-design/icons@4.7.0
| +-- @ant-design/react-slick@0.28.4
| +-- @babel/runtime@7.12.5 deduped
| +-- @ctrl/tinycolor@3.4.0
| +-- classnames@2.2.6 deduped
| +-- copy-to-clipboard@3.3.1
| +-- lodash@4.17.21 deduped
| +-- memoize-one@6.0.0
| +-- moment@2.29.3 deduped
| +-- rc-cascader@3.5.0
| +-- rc-checkbox@2.3.2
| +-- rc-collapse@3.1.4
| +-- rc-dialog@8.8.1
| +-- rc-drawer@4.4.3
| +-- rc-dropdown@3.5.2
| +-- rc-field-form@1.26.4
| +-- rc-image@5.6.2
| +-- rc-input@0.0.1-alpha.7
| +-- rc-input-number@7.3.4
| +-- rc-mentions@1.7.1
| +-- rc-menu@9.5.5
| +-- rc-motion@2.6.0
| +-- rc-notification@4.6.0
| +-- rc-pagination@3.1.16
| +-- rc-picker@2.6.9
| +-- rc-progress@3.2.4
| +-- rc-rate@2.9.1
| +-- rc-resize-observer@1.2.0
| +-- rc-segmented@2.1.0
| +-- rc-select@14.1.3
| +-- rc-slider@10.0.0
| +-- rc-steps@4.1.4
| +-- rc-switch@3.2.2
| +-- rc-table@7.24.2
| +-- rc-tabs@11.13.0
| +-- rc-textarea@0.3.7
| +-- rc-tooltip@5.1.1
| +-- rc-tree@5.5.0
| +-- rc-tree-select@5.3.0
| +-- rc-trigger@5.2.18
| +-- rc-upload@4.3.3
| +-- rc-util@5.21.4
| `-- scroll-into-view-if-needed@2.2.29
+-- antd-mask-input@2.0.7
| `-- imask@6.4.2
+-- clsx@1.1.1
+-- core-js@3.8.3
+-- craco-antd@2.0.0
| +-- babel-plugin-import@1.13.5
| +-- craco-less@2.0.0
| `-- less-vars-to-js@1.3.0
+-- eol-converter-cli@1.0.8
| +-- eol@0.9.1
| `-- glob@7.1.6 deduped
+-- eslint@7.20.0
| +-- @babel/code-frame@7.12.11
| +-- @eslint/eslintrc@0.3.0
| +-- ajv@6.12.6
| +-- chalk@4.1.0
| +-- cross-spawn@7.0.3
| +-- debug@4.3.1
| +-- doctrine@3.0.0
| +-- enquirer@2.3.6
| +-- eslint-scope@5.1.1
| +-- eslint-utils@2.1.0
| +-- eslint-visitor-keys@2.0.0
| +-- espree@7.3.1
| +-- esquery@1.4.0
| +-- esutils@2.0.3
| +-- file-entry-cache@6.0.0
| +-- functional-red-black-tree@1.0.1
| +-- glob-parent@5.1.2
| +-- globals@12.4.0
| +-- ignore@4.0.6
| +-- import-fresh@3.3.0
| +-- imurmurhash@0.1.4
| +-- is-glob@4.0.1
| +-- js-yaml@3.14.1
| +-- json-stable-stringify-without-jsonify@1.0.1
| +-- levn@0.4.1
| +-- lodash@4.17.21 deduped
| +-- minimatch@3.0.4
| +-- natural-compare@1.4.0
| +-- optionator@0.9.1
| +-- progress@2.0.3 deduped
| +-- regexpp@3.1.0
| +-- semver@7.3.2 deduped
| +-- strip-ansi@6.0.0
| +-- strip-json-comments@3.1.1
| +-- table@6.0.7
| +-- text-table@0.2.0
| `-- v8-compile-cache@2.2.0
+-- eslint-config-prettier@7.2.0
+-- eslint-plugin-prettier@3.3.1
| `-- prettier-linter-helpers@1.0.0
+-- exceljs@4.2.1
| +-- archiver@5.3.0
| +-- dayjs@1.10.4
| +-- fast-csv@4.3.6
| +-- jszip@3.10.0
| +-- readable-stream@3.6.0
| +-- saxes@5.0.1
| +-- tmp@0.2.1 deduped
| +-- unzipper@0.10.11
| `-- uuid@8.3.2 deduped
+-- fetch-mock@9.11.0
| +-- @babel/core@7.12.3
| +-- @babel/runtime@7.12.5 deduped
| +-- core-js@3.8.3 deduped
| +-- debug@4.3.1 deduped
| +-- glob-to-regexp@0.4.1
| +-- is-subset@0.1.1
| +-- lodash.isequal@4.5.0
| +-- path-to-regexp@2.4.0
| +-- querystring@0.2.0
| `-- whatwg-url@6.5.0
+-- file-saver@2.0.5
+-- gherkin-testcafe@5.3.0
| +-- @cucumber/cucumber@7.3.2
| +-- @cucumber/cucumber-expressions@12.1.3 deduped
| `-- @cucumber/gherkin-streams@3.0.0
+-- glob@7.1.6
| +-- fs.realpath@1.0.0
| +-- inflight@1.0.6
| +-- inherits@2.0.4
| +-- minimatch@3.0.4 deduped
| +-- once@1.4.0
| `-- path-is-absolute@1.0.1
+-- html-to-image@1.9.0
+-- i18next@19.8.7
| `-- @babel/runtime@7.12.5 deduped
+-- jest-serializer-html@7.0.0
| `-- diffable-html@4.0.0
+-- lz-string@1.4.4
+-- moment@2.29.3
+-- moment-business@3.0.1
| +-- contained-periodic-values@1.0.0
| `-- skipped-periodic-values@1.0.1
+-- mousetrap@1.6.5
+-- oidc-client@1.11.4
| +-- acorn@7.4.1
| +-- base64-js@1.5.1
| +-- core-js@3.8.3 deduped
| +-- crypto-js@4.0.0
| `-- serialize-javascript@4.0.0
+-- prettier@2.2.1
+-- UNMET PEER DEPENDENCY react@18.1.0
| `-- loose-envify@1.4.0
+-- react-app-polyfill@2.0.0
| +-- core-js@3.8.3 deduped
| +-- object-assign@4.1.1
| +-- promise@8.1.0
| +-- raf@3.4.1
| +-- regenerator-runtime@0.13.7
| `-- whatwg-fetch@3.5.0
+-- react-device-detect@1.17.0
| `-- ua-parser-js@0.7.28
+-- UNMET PEER DEPENDENCY react-dom@18.1.0
| +-- loose-envify@1.4.0 deduped
| `-- scheduler@0.22.0
+-- react-i18next@11.8.6
| +-- @babel/runtime@7.12.5 deduped
| `-- html-parse-stringify2@2.0.1
+-- react-number-format@4.4.4
| `-- prop-types@15.7.2
+-- react-redux@8.0.2
| +-- @babel/runtime@7.12.5 deduped
| +-- @types/hoist-non-react-statics@3.3.1 deduped
| +-- @types/use-sync-external-store@0.0.3
| +-- hoist-non-react-statics@3.3.2 deduped
| +-- react-is@18.1.0
| `-- use-sync-external-store@1.1.0
+-- react-router-dom@6.0.0
| `-- react-router@6.0.0
+-- UNMET PEER DEPENDENCY react-scripts@5.0.1
| +-- @babel/core@7.18.2
| +-- @pmmmwh/react-refresh-webpack-plugin@0.5.7
| +-- @svgr/webpack@5.5.0
| +-- babel-jest@27.5.1
| +-- babel-loader@8.2.5
| +-- babel-plugin-named-asset-import@0.3.8
| +-- babel-preset-react-app@10.0.1
| +-- bfj@7.0.2
| +-- browserslist@4.20.3
| +-- camelcase@6.3.0
| +-- case-sensitive-paths-webpack-plugin@2.4.0
| +-- css-loader@6.7.1
| +-- css-minimizer-webpack-plugin@3.4.1
| +-- dotenv@10.0.0
| +-- dotenv-expand@5.1.0
| +-- UNMET PEER DEPENDENCY eslint@8.16.0
| +-- eslint-config-react-app@7.0.1
| +-- eslint-webpack-plugin@3.1.1
| +-- file-loader@6.2.0
| +-- fs-extra@10.1.0
| +-- UNMET OPTIONAL DEPENDENCY fsevents@2.3.2
| +-- html-webpack-plugin@5.5.0
| +-- identity-obj-proxy@3.0.0
| +-- jest@27.5.1
| +-- jest-resolve@27.5.1
| +-- jest-watch-typeahead@1.1.0
| +-- mini-css-extract-plugin@2.6.0
| +-- postcss@8.4.14
| +-- postcss-flexbugs-fixes@5.0.2
| +-- postcss-loader@6.2.1
| +-- postcss-normalize@10.0.1
| +-- postcss-preset-env@7.6.0
| +-- prompts@2.4.2
| +-- react-app-polyfill@3.0.0
| +-- react-dev-utils@12.0.1
| +-- react-refresh@0.11.0
| +-- resolve@1.22.0
| +-- resolve-url-loader@4.0.0
| +-- sass-loader@12.6.0
| +-- semver@7.3.7
| +-- source-map-loader@3.0.1
| +-- style-loader@3.3.1
| +-- tailwindcss@3.0.24
| +-- terser-webpack-plugin@5.3.1
| +-- webpack@5.72.1
| +-- webpack-dev-server@4.9.0
| +-- webpack-manifest-plugin@4.1.1
| `-- workbox-webpack-plugin@6.5.3
+-- react-tiny-fab@4.0.2
+-- redux@4.1.2
| `-- @babel/runtime@7.12.5 deduped
+-- redux-logger@3.0.6
| `-- deep-diff@0.3.8
+-- redux-mock-store@1.5.4
| `-- lodash.isplainobject@4.0.6
+-- redux-oidc@4.0.0-beta1
+-- redux-thunk@2.3.0
+-- reselect@4.0.0
+-- serve@11.3.2
| +-- @zeit/schemas@2.6.0
| +-- ajv@6.5.3
| +-- arg@2.0.0
| +-- boxen@1.3.0
| +-- chalk@2.4.1
| +-- clipboardy@1.2.3
| +-- compression@1.7.3
| +-- serve-handler@6.1.3
| `-- update-check@1.5.2
+-- swagger-typescript-api@4.4.0
| +-- @types/swagger-schema-official@2.0.21
| +-- axios@0.21.4
| +-- commander@6.2.1
| +-- eta@1.12.1
| +-- js-yaml@4.0.0
| +-- lodash@4.17.21 deduped
| +-- make-dir@3.1.0
| +-- nanoid@3.3.4
| +-- prettier@2.2.1 deduped
| +-- swagger-schema-official@2.0.0-bab6bed
| +-- swagger2openapi@7.0.5
| `-- typescript@4.1.5 deduped
+-- testcafe@1.18.6
| +-- @babel/core@7.12.3 deduped
| +-- @babel/plugin-proposal-async-generator-functions@7.12.1
| +-- @babel/plugin-proposal-class-properties@7.12.1
| +-- @babel/plugin-proposal-decorators@7.18.2
| +-- @babel/plugin-proposal-object-rest-spread@7.12.1
| +-- @babel/plugin-proposal-private-methods@7.17.12
| +-- @babel/plugin-syntax-dynamic-import@7.8.3
| +-- @babel/plugin-syntax-import-meta@7.10.4
| +-- @babel/plugin-transform-async-to-generator@7.12.1
| +-- @babel/plugin-transform-exponentiation-operator@7.12.1
| +-- @babel/plugin-transform-for-of@7.12.1
| +-- @babel/plugin-transform-runtime@7.18.2
| +-- @babel/preset-env@7.12.11
| +-- @babel/preset-flow@7.17.12
| +-- @babel/preset-react@7.12.10
| +-- @babel/runtime@7.12.5 deduped
| +-- @miherlosev/esm@3.2.26
| +-- @types/node@12.20.52
| +-- async-exit-hook@1.1.2
| +-- babel-plugin-module-resolver@4.1.0
| +-- babel-plugin-syntax-trailing-function-commas@6.22.0
| +-- bin-v8-flags-filter@1.2.0
| +-- bowser@2.11.0
| +-- callsite@1.0.0
| +-- callsite-record@4.1.4
| +-- chai@4.3.4
| +-- chalk@2.4.2
| +-- chrome-remote-interface@0.30.1
| +-- coffeescript@2.7.0
| +-- commander@8.3.0
| +-- debug@4.3.1 deduped
| +-- dedent@0.4.0
| +-- del@3.0.0
| +-- device-specs@1.0.0
| +-- diff@4.0.2
| +-- elegant-spinner@1.0.1
| +-- emittery@0.4.1
| +-- endpoint-utils@1.0.2
| +-- error-stack-parser@1.3.6
| +-- execa@4.1.0
| +-- globby@11.1.0
| +-- graceful-fs@4.2.4
| +-- graphlib@2.1.8
| +-- humanize-duration@3.27.2
| +-- import-lazy@3.1.0
| +-- indent-string@1.2.2
| +-- is-ci@1.2.1
| +-- is-docker@2.1.1
| +-- is-glob@2.0.1
| +-- is-stream@2.0.1
| +-- json5@2.1.3
| +-- lodash@4.17.21 deduped
| +-- log-update-async-hook@2.0.7
| +-- make-dir@3.1.0
| +-- mime-db@1.44.0
| +-- moment@2.29.3 deduped
| +-- moment-duration-format-commonjs@1.0.1
| +-- mustache@2.3.2
| +-- nanoid@3.3.4 deduped
| +-- os-family@1.1.0
| +-- parse5@1.5.1
| +-- pify@2.3.0
| +-- pinkie@2.0.4
| +-- pngjs@3.4.0
| +-- pretty-hrtime@1.0.3
| +-- promisify-event@1.0.0
| +-- qrcode-terminal@0.10.0
| +-- read-file-relative@1.2.0
| +-- replicator@1.0.5
| +-- resolve-cwd@1.0.0
| +-- resolve-from@4.0.0
| +-- sanitize-filename@1.6.3
| +-- semver@5.7.1
| +-- source-map-support@0.5.19
| +-- strip-bom@2.0.0
| +-- testcafe-browser-tools@2.0.23
| +-- testcafe-hammerhead@24.5.18
| +-- testcafe-legacy-api@5.1.4
| +-- testcafe-reporter-dashboard@0.2.5
| +-- testcafe-reporter-json@2.2.0
| +-- testcafe-reporter-list@2.1.0
| +-- testcafe-reporter-minimal@2.1.0
| +-- testcafe-reporter-spec@2.1.1
| +-- testcafe-reporter-xunit@2.2.1
| +-- time-limit-promise@1.0.4
| +-- tmp@0.0.28
| +-- tree-kill@1.2.2
| +-- typescript@3.9.10
| `-- unquote@1.1.1
+-- testcafe-browser-provider-selenium@1.2.0
| +-- @babel/runtime-corejs2@7.16.7
| +-- fs@0.0.2
| `-- selenium-webdriver@4.1.1
+-- ts-polyfill@3.8.2
| `-- core-js@3.8.3 deduped
+-- typescript@4.1.5
+-- uuid@8.3.2
`-- web-vitals@0.2.4

```

**Comment by Arthy000** [comment] 2022-06-07 12:03
Very weird. Have you tried deleting your node_modules and reinstalling from scratch like Kabomi did?

**Comment by kel666** [comment] 2022-06-07 14:27
I updated gherkin-testcafe to 5.4.0 and cucumber to 8.2.2, delete node_modules, and it worked! Tnx a lot!

But I noticed a strange behaviour when testcontroller fails waiting for some DOM, I receive this error:

```
ERROR The "reportTestDone" method of the "gtc-reporter-spec" reporter produced an uncaught error. Error details:
TypeError: Cannot read property 'concat' of undefined
    at C:\git\USP.Commodity.UI\node_modules\gherkin-testcafe\src\reporters\gtc-reporter-spec.js:77:42
    at Array.map (<anonymous>)
    at ReporterPluginHost.reportTestDone (C:\git\USP.Commodity.UI\node_modules\gherkin-testcafe\src\reporters\gtc-reporter-spec.js:77:8)
    at Reporter.dispatchToPlugin (C:\git\USP.Commodity.UI\node_modules\testcafe\src\reporter\index.ts:160:38)
    at Reporter._shiftTestQueue (C:\git\USP.Commodity.UI\node_modules\testcafe\src\reporter\index.ts:329:24)
    at Reporter._resolveTestItem (C:\git\USP.Commodity.UI\node_modules\testcafe\src\reporter\index.ts:393:20)
    at Reporter._onTaskTestRunDoneHandler (C:\git\USP.Commodity.UI\node_modules\testcafe\src\reporter\index.ts:538:24)
    at C:\git\USP.Commodity.UI\node_modules\testcafe\src\reporter\index.ts:185:68
    at C:\git\USP.Commodity.UI\node_modules\testcafe\node_modules\emittery\index.js:69:13
    at Array.map (<anonymous>)
    at MessageBus.emit (C:\git\USP.Commodity.UI\node_modules\testcafe\node_modules\emittery\index.js:67:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at C:\git\USP.Commodity.UI\node_modules\testcafe\src\runner\task\index.ts:92:13

```

I remember the before these package updates the error reported me the step line of code where the error occurred, which was very useful.
Any idea about this?

tnx
Fabio

**Comment by Arthy000** [comment] 2022-06-07 14:56
Yeah it should still work, 5.4.0 contains a brand new feature that I just added. I tested it but my test cases are limited, so it's probably a bug in the new reporter. You can work around it by using `-r spec` if you use the CLI or by using `runner.reporter("spec")` if you use the API

**Comment by kel666** [comment] 2022-06-07 15:16
Tnx for the hint.

The failing steps is on a typeText for a DOM not found:

```
Feature: No Regression for: Enabling the indicative price
 × Scenario: Legal Entity SpA. Check Indicative price for BulletSwap and ALUMINIUM 3M

   1) The specified selector does not match any element in the DOM tree.

       > | Selector('div[aria-label=fixing_date] input')

      Browser: Chrome 101.0.4951.54 / Windows 10

         72 |  },
         73 |);
         74 |
         75 |When(/on (.*) Date I select (.*)/i, async (t: TestController, [calendarField, date]: [string, string]) => {
         76 |  const fld = Selector(`div[aria-label=${page.fixFieldName(calendarField + ' Date')}] input`);
       > 77 |  await t.typeText(fld, date);
         78 |  await t.pressKey('tab');
         79 |});
         80 |
         81 |When(/I open dates dialog/i, async (t: TestController) => {
         82 |  await t.click(Selector('div.datesBox a'));

         at <anonymous> (C:\git\USP.Commodity.UI\src\e2etest\steps.ts:77:11)
         at <anonymous> (C:\git\USP.Commodity.UI\src\e2etest\steps.ts:9:71)
         at __awaiter (C:\git\USP.Commodity.UI\src\e2etest\steps.ts:5:12)
         at <anonymous> (C:\git\USP.Commodity.UI\src\e2etest\steps.ts:75:106)
         at GherkinTestcafeCompiler._runStep (C:\git\USP.Commodity.UI\node_modules\gherkin-testcafe\src\compiler.js:300:12)
         at GherkinTestcafeCompiler._resolveAndRunStepDefinition
      (C:\git\USP.Commodity.UI\node_modules\gherkin-testcafe\src\compiler.js:288:21)
         at <anonymous> (C:\git\USP.Commodity.UI\node_modules\gherkin-testcafe\src\compiler.js:192:28)
```

**Comment by Arthy000** [comment] 2022-06-07 16:50
Could you provide me with a small example where you can reproduce the `TypeError: Cannot read property 'concat' of undefined` issue?
From what I've seen in cucumber code, the reporter should most of the time receive "Context", "Action" or "Outcome" as a step type. 
The only other possible value is "Unknown" but that would mean something is going on with your feature file that I have never encountered in my tests.

**Comment by Arthy000** [comment] 2022-06-08 06:51
As the original issue is resolved, I'll close this thread. 
Another issue (#89) has been opened with exactly the same problem so feel free to follow and comment there instead :)

**Closed by Arthy000** 2022-06-08 06:51 UTC
