### ISSUE TITLE
Is it possible to see step from feature file in the report testcafe-reporter-cucumber-json

### ISSUE THREAD

**Issue by dskochubey** [Arthy000/gherkin-testcafe#25] opened 2021-01-29 21:18 UTC
Hi!

I have run examples from this repo, saved the result to the [testcafe-reporter-cucumber-json](https://www.npmjs.com/package/testcafe-reporter-cucumber-json) and then generate HTML report using [multiple-cucumber-html-reporter](https://www.npmjs.com/package/testcafe-reporter-cucumber-json#to-generate-the-html-report). In the json and HTML report section `steps` doesn't contain any steps from feature files. Am I missing some steps\setting or this is expected?

**Comment by Arthy000** [comment] 2021-02-01 11:35
Hello,

I'm sorry but I can't really help you here.
This reporter was designed for TestCafe, and there are no "steps" in a TestCafe script.

From what I understand, the goal of `testcafe-reporter-cucumber-json` is not to handle cucumber tests properly (because TestCafe does not), but to output a report formatted so it can be merged with `multiple-cucumber-html-reporter`. That format includes a `steps` section, even if there is nothing to put in there.

**Comment by dskochubey** [comment] 2021-02-04 19:25
Thank you for your explanation. So sad to hear that. That makes no sense to use Cucumber + Testcafe if there is no way to printout regular report with steps :(

**Comment by Arthy000** [comment] 2021-02-04 21:56
I don't find having the steps in the report that important, personally, but I'm sorry if this is a deal breaker for you :(

**Closed by Arthy000** 2021-02-04 21:56 UTC
