### ISSUE TITLE
Testcafe 3.0 support

### ISSUE THREAD

**Issue by kojoru** [Arthy000/gherkin-testcafe#133] opened 2023-06-27 08:36 UTC
Hi,

Can I ask you to investigate v3 support for Testcafe? 

Is there anything we can do to facilitate peer dependencies upgrade from our side? I would be happy to assist, if so.

**Comment by Arthy000** [comment] 2023-06-27 18:12
Hi @kojoru, 

Not to worry, I'll start working on it right away. I admit I haven't checked on TestCafe's versions for a while now.

It's usually a pretty straightforward process, so if we are lucky you can even expect a new release tonight (well it really depends on your timezone but you get the idea)

**Comment by Arthy000** [comment] 2023-06-27 20:14
Okay, so it looks like there a few breaking changes, nothing I can't work out though.

HOWEVER, there is also an issue which seems to come from TC3 itself, I'd say a bug on their side or in one of their dependencies.
Basically, one of my most basic examples fails flakily, with an unhandled promise rejection in Chrome remote interface.
Chrome is up-to-date and the issue doesn't seem to occur on Firefox (though, as it is flaky, it could be very rare)
Full disclosure, I use a Mac so maybe the issue is limitted to my OS.
<img width="889" alt="Screenshot 2023-06-27 at 22 12 12" src="https://github.com/Arthy000/gherkin-testcafe/assets/1800622/21d0eb0b-a90b-4624-80e4-cd07edd29fb0">

IMHO it would be better to wait for TC version 3.0.1 before upgrading, the current version is pretty new and I usually wait for a week or two before attempting the update. 

However if you're really confident you can work around the issue or you really need some new feature, I'll publish it despite my lack of confidence (probably as a rc version)

**Comment by mokone91** [comment] 2023-08-01 09:57
it seems https://github.com/DevExpress/testcafe/issues/7852 is fixed now

**Comment by Arthy000** [comment] 2023-08-05 14:58
It was not really a blocking issue, but earlier versions of TC3 were not stable enough to my taste.
Version 3.1.0 seems to have solved the issues I found while testing, so I made the change and just released the new version.

**Closed by Arthy000** 2023-08-05 14:58 UTC
